### ISSUE TITLE
daily mixes

### ISSUE THREAD

**Issue by fastcolors** [custom-cards/spotify-card#24]
would it be possible to retrieve the infinite playlists spotify creates (daily mix 1 - 2 - 3 etc ) and start them from card?

**Comment by fastcolors** [comment]
found this:

https://github.com/vdesabou/alfred-spotify-mini-player/issues/202#issuecomment-328083367

apparently there's some hiding undocumented spotify super secret api...

**Comment by fondberg** [comment]
In not sure what the ask is here. Is it to list the daily mixes? Unfortunately there is no way to control the sorting of the playlists returned but for me they are shown.

**Comment by fastcolors** [comment]
I don't think it has anything to do with sorting, I just have a single user made playlist, and the card retrieves 10, so I should see the daily mix 1 / 2 / 3 etc.. but they don't show up.

I went on a search on the forums and discovered it's a known "issue" (although not a real "issue") just the "official" api don't support it, but if you read the article I attached, it does explain how to get them working!

I have such little knowledge of api calls and JS that it would take me years to achieve any result... on the other hand You... :-) eheheh.

Any effort is appreciated, if You think this is pointeless I will live without it <3

Cheers, and thanks for the great card.

PS: you're dying you see the daily mixes in your playlist list? not the "discover weekly".. i'm talking about th infinite playlists created by spotify on following listening habits..

![Schermata 2019-09-08 alle 09 45 22](https://user-images.githubusercontent.com/2766945/64485183-80e6ba80-d21d-11e9-85b5-6316ebe0f823.png)

**Comment by fondberg** [comment]
I might have stared my mix lists in the spotify app.
Ca u try that?

**Comment by fastcolors** [comment]
I tried saving them as a playlist, but spotify just stores a few songs and the "infinite" daily mix becomes a "finite" playlist. Considering I mainly keep it playing all day at work, the "infinite" attribute is the lovely part for me... hope it makes sense.

**Comment by fondberg** [comment]
Oh. I need to check if that is the same for me. Regarding the super hidden feature it will be hard to implement here as this card uses the normal open web api.

**Comment by exetico** [comment]
Maybe an alternative could be:
https://api.spotify.com/v1/browse/featured-playlists

However, that's not daily mixed, for sure :-)

I could be interesting to check, if it's actually an option to use the same commands, as for the normal Spotify client, on my laptop :-)

**Comment by fondberg** [comment]
Sent a mail to me?

**Comment by fondberg** [comment]
@exetico i finaööy för som time to experiment with getting daily mixes as well as made-for-x. Both seems to only be available from the browser and using the token from the web api seems to be too weak.
I did implement featured playlists and I wanted to ask if this would be of interest or if I should continue with trying to get playlists through daily mixes through spotcast which has the more powerful app token.
Wdyt?

**Comment by exetico** [comment]
The featured playlist is a good thing to have, however, the daily mixes is awesome (at least, if you ask me). I actually thought that you could use the API token, to access the Web API too. But i'm not sure if i tested that, or not.

I guess it would make sense to integrate the Daily Mixes in Spotcast. Well, at lease, i would like that as an option. From a user perspective, i'm not sure what the best thing is.

However, using Spotcast to trigger Dailiy Mix 1-4 and so, would be great from m POV.

**Comment by fondberg** [comment]
@exetico I decided to do both. For now (in the newly released 1.10) it is possible to set a new configuration parameter called featuredPlaylists which takes a boolean and if true it will display those playlists instead of the users playlists.

**Comment by exetico** [comment]
Thanks fondberg! :-) 

![image](https://user-images.githubusercontent.com/3549445/71578962-9ba9ab80-2afa-11ea-9402-abf2170cf1b6.png)


I've scrollbars on my Spotify Card, after the last update. I'm not sure if it's related to the height-feature, however, they are shown at all times.

**Comment by fondberg** [comment]
hmmm, i guess i can fix the horizontal quite fast but the vertical must be due to height issues

**Comment by fondberg** [comment]
@exetico I played araound with mine and can't reproduce the horizontal issue. The outer vertical scroll is not added by my code. You must be using some custom code which wraps the card somehow. The inner vertical scrollbar is a tuning between height and limit.

I will however release a new version with some small fixes and bumps to deps where I will remove the horizontal scroll on overflow

**Comment by fondberg** [comment]
<img width="526" alt="Screenshot 2020-01-05 at 15 06 19" src="https://user-images.githubusercontent.com/10739838/71781264-f5afe280-2fcc-11ea-9f85-f45c9d37061c.png">
<img width="288" alt="Screenshot 2020-01-05 at 15 03 57" src="https://user-images.githubusercontent.com/10739838/71781265-f6487900-2fcc-11ea-95ca-75b9bbf690a9.png">

**Comment by fondberg** [comment]
<img width="555" alt="Screenshot 2020-01-05 at 15 08 32" src="https://user-images.githubusercontent.com/10739838/71781304-4e7f7b00-2fcd-11ea-8179-62a749b2d1fb.png">

**Comment by exetico** [comment]
It's still a problem here, in both Chrome and Firefox - so it must be my theme.


![image](https://user-images.githubusercontent.com/3549445/72175584-bf170500-33dc-11ea-8d3b-fcdbddf247ba.png)

So, i must check what's going on, and fix it - and report it in the right repo. Thanks for checking :-)

**Comment by fondberg** [comment]
Hey friends! I just released spotcast v.2.6.0 which amongst other things adds a web socket api to retrieve daily mixes playlists. I also released v1.2.0 of this card which adds support for it using 
`dailyMixes=true` in the conf for the card (remove featuredPlaylists parameter before using it).

Can you try it out?

**Comment by fondberg** [comment]
Did anyone give it a try?

**Comment by exetico** [comment]
Hi friend. I'm sorry! I'll give it a try tomorrow :-)

**Comment by bocsitomcsi** [comment]
Works like a charm:
![image](https://user-images.githubusercontent.com/6852958/73066847-731d9300-3ea7-11ea-866b-56270ee4499f.png)

**Comment by exetico** [comment]
![image](https://user-images.githubusercontent.com/3549445/73067351-bfb59e00-3ea8-11ea-8bc3-1d5c42ea63ad.png)
 
Confirmed OK from my end, too. I'm still seeing the scrollbar and so, but i'll fix that at some point. Currently it's not that big of a deal.

Thanks for implementing it :-)

**Comment by fondberg** [comment]
Great!
